### ISSUE TITLE
EAGLE files?

### ISSUE THREAD

**Issue by FRVisser** [lgxlogic/CBB-XBEE#1]
As stated on [elinux wiki](http://elinux.org/BeagleBone_XBee_proto_cape):

> Open Source	Yes
> System Reference Manual	Yes
> Schematics	EAGLE, PDF
> PCB Files	EAGLE
> Gerber Files	Yes
> Bills of Materials	Yes

So, where are the files?

**Comment by geurjas** [comment]
We would like to get our hands on those gerber and eagle file, because we can not order them any more at logic supply.  Can you please upload them, its open source hardware I believe.

Thanks in advance,
 Jasper

**Comment by rgroeneveld** [comment]
Hi Jasper, the files are uploaded now.
